# -*- coding: utf-8 -*-
"""AgeCalculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10XEL286Wg8PqGnI4w_jRkNeHToOD2lEZ
"""

from datetime import datetime

def age_calculator():
    try:
        birth_input = input("Enter your birth date (mm/dd/yyyy): ")

        # Validate format
        birth_date = datetime.strptime(birth_input, "%m/%d/%Y")

        # Calculate age
        today = datetime.today()
        age = today.year - birth_date.year

        # Adjust age if birthday hasn't come yet this year
        if (today.month, today.day) < (birth_date.month, birth_date.day):
            age -= 1

        # Convert to European format
        european_format = birth_date.strftime("%d/%m/%Y")

        print(f"\nYour current age: {age} years")
        print(f"Birthdate in European format: {european_format}")

    except ValueError:
        print("Invalid date format or invalid date! Please enter in mm/dd/yyyy format.")

    except Exception as e:
        print("An unexpected error occurred:", e)

age_calculator()