# -*- coding: utf-8 -*-
"""PrimeNumberGenerator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1reSAPy0gcaiouaAlHNAnBmjeDH5EqUAI
"""

def is_prime(n):
    # Check if a number is prime
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

def prime_generator():
    try:
        # Get user inputs
        start = int(input("Enter range start (positive integer): "))
        end = int(input("Enter range end (positive integer): "))

        # Validate inputs
        if start <= 0 or end <= 0:
            print("Both numbers must be positive integers.")
            return
        if start > end:
            print("Start cannot be greater than end.")
            return

        # Collect prime numbers
        primes = [num for num in range(start, end + 1) if is_prime(num)]

        if not primes:
            print("No prime numbers found in this range.")
            return

        # Print 10 primes per line
        count = 0
        for p in primes:
            print(f"{p:4}", end=" ")
            count += 1
            if count == 10:
                print()
                count = 0
        print()

    except ValueError:
        # Handle non-integer input
        print("Invalid input! Please enter positive integers only.")

    except Exception as e:
        # Handle other unexpected errors
        print("An unexpected error occurred:", e)

prime_generator()