# -*- coding: utf-8 -*-
"""StudentMarkProcessor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Ax3wS6NGu7iJ7b6iF9RD0ETamnwxYe7
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile students.txt
# IT202001,78,65
# IT202002,55,48
# IT202003,90,80
# IT202004,35,40
# IT202005,67,72
# IT202006,88,91
# IT202007,45,55
# IT202008,30,25
# IT202009,74,68
# IT202010,59,61
# IT202011,82,77
# IT202012,49,52
# IT202013,93,88
# IT202014,41,39
# IT202015,64,70
#

import numpy as np

def compute_grade(mark):
    if mark >= 70:
        return 'A'
    elif mark >= 60:
        return 'B'
    elif mark >= 50:
        return 'C'
    elif mark >= 40:
        return 'D'
    else:
        return 'F'

def process_student_marks(input_file, output_file):
    try:
        with open(input_file, "r") as f:
            lines = f.readlines()

        records = []

        for line in lines:
            parts = line.strip().split(",")

            if len(parts) != 3:
                print(f"Invalid line skipped: {line.strip()}")
                continue

            reg, exam, coursework = parts

            try:
                exam = float(exam)
                coursework = float(coursework)
            except ValueError:
                print(f"Invalid marks skipped: {line.strip()}")
                continue

            overall = exam * 0.60 + coursework * 0.40
            grade = compute_grade(overall)

            records.append((reg, exam, coursework, overall, grade))

        if not records:
            print("No valid student records found.")
            return

        dtype = [
            ('regno', 'U20'),
            ('exam', 'f4'),
            ('coursework', 'f4'),
            ('overall', 'f4'),
            ('grade', 'U2')
        ]

        data = np.array(records, dtype=dtype)
        data = np.sort(data, order='overall')[::-1]

        with open(output_file, "w") as f:
            f.write("RegNo,Exam,Coursework,Overall,Grade\n")
            for row in data:
                f.write(f"{row['regno']},{row['exam']},{row['coursework']},{row['overall']:.2f},{row['grade']}\n")

        grades, counts = np.unique(data['grade'], return_counts=True)

        print("\nGrade Statistics:")
        for g, c in zip(grades, counts):
            print(f"  Grade {g}: {c} student(s)")

        print("\nProcessing complete! Output saved in:", output_file)

    except FileNotFoundError:
        print("Error: Input file not found.")
    except PermissionError:
        print("Error: No permission to read/write files.")
    except Exception as e:
        print("Unexpected error occurred:", e)


# Run the program
process_student_marks("students.txt", "results.txt")

!cat results.txt