# -*- coding: utf-8 -*-
"""Weather Data Fetcher & Analyzer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F2cK22U-d1WmzxYrUS6WlRe_XQDROpMv
"""

!pip install requests

import requests  # To make API calls
import csv       # To write data to CSV files
from datetime import datetime  # To add timestamp


def fetch_weather(city: str, api_key: str) -> dict:
    """
    Fetch weather data from OpenWeatherMap API.
    """

    try:
        # Build the URL for API call
        url = f"https://api.openweathermap.org/data/2.5/weather?q={city}&appid={api_key}&units=metric"

        # Send GET request to the API
        response = requests.get(url)

        # Check if request was successful
        response.raise_for_status()

        # Return the JSON result as a Python dictionary
        return response.json()

    except requests.exceptions.HTTPError:
        # Handles cases like invalid city or wrong API key
        print("Error: Invalid city name or API key.")
        return None

    except requests.exceptions.ConnectionError:
        # Handles internet connection problems
        print("Error: Network connection issue.")
        return None

    except Exception as e:
        # Handles any unexpected error
        print("Unexpected error:", e)
        return None



def analyze_weather(weather_data: dict) -> str:
    """
    Analyze temperature, wind, humidity → return summary string.
    """

    # Extract temperature from JSON
    temp = weather_data["main"]["temp"]

    # Extract wind speed
    wind = weather_data["wind"]["speed"]

    # Extract humidity
    humidity = weather_data["main"]["humidity"]

    # Temperature classification
    if temp <= 10:
        summary = "Cold (≤10°C)"
    elif temp <= 24:
        summary = "Mild (11–24°C)"
    else:
        summary = "Hot (≥25°C)"

    # Add warnings
    if wind > 10:
        summary += " | High wind alert!"
    if humidity > 80:
        summary += " | Humid conditions!"

    return summary



def log_weather(city: str, filename: str, api_key: str):
    """
    Fetch weather → analyze → append to CSV file.
    """

    # Step 1: Fetch the weather data
    data = fetch_weather(city, api_key)

    # Stop if fetch failed
    if data is None:
        return

    # Step 2: Analyze conditions
    analysis = analyze_weather(data)

    # Step 3: Prepare data to save
    temp = data["main"]["temp"]
    wind = data["wind"]["speed"]
    humidity = data["main"]["humidity"]
    description = data["weather"][0]["description"]
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Step 4: Append to CSV file
    # newline='' prevents blank rows in CSV
    with open(filename, "a", newline="") as file:
        writer = csv.writer(file)

        # Write row: timestamp, city, temp, humidity, wind, description, analysis
        writer.writerow([timestamp, city, temp, humidity, wind, description, analysis])

    print(f"Weather logged for {city} → {filename}")

api_key = "2c20fe03201a298fe8d66e640024f7d0"

# Get city name from user
city = input("Enter city name: ")

log_weather(city, "weather_log.csv", api_key)

import pandas as pd
df = pd.read_csv("weather_log.csv", header=None,
                 names=["Timestamp","City","Temp","Humidity","Wind","Description","Analysis"])
df