# -*- coding: utf-8 -*-
"""Sona_S_GENAI_WEEK2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10_-uPUpYCHtCLQI1JilgnNmDJVu6JaY1
"""

# ---------------- Task 1: Python Basics & Operators ----------------

# Accept two numbers
a = float(input("Enter first number: "))
b = float(input("Enter second number: "))

# Arithmetic
add = a + b
sub = a - b
mul = a * b
div = a / b if b != 0 else " Division by zero"
mod = a % b if b != 0 else " Mod by zero"
power = a ** b

# Comparison + Logical
print("\n---  Arithmetic Results ---")
print(f"{a} + {b} = {add}")
print(f"{a} - {b} = {sub}")
print(f"{a} × {b} = {mul}")
print(f"{a} ÷ {b} = {div}")
print(f"{a} % {b} = {mod}")
print(f"{a} ^ {b} = {power}")

print("\n---  Comparison Operators ---")
print(f"{a} > {b} : {a > b}")
print(f"{a} < {b} : {a < b}")
print(f"{a} == {b} : {a == b}")
print(f"{a} != {b} : {a != b}")

print("\n---  Logical Operators ---")
print(f"({a}>0) and ({b}>0) → {(a>0) and (b>0)}")
print(f"({a}>0) or ({b}>0) → {(a>0) or (b>0)}")
print(f"not ({a}>{b}) → {not(a>b)}")

# ---------------- Task 2: Lists and Arrays (User Input) ----------------

import numpy as np
import random

#  Create list of 10 random integers
numbers = [random.randint(1, 100) for _ in range(10)]
print("Original List:", numbers)

#  Add element from user
add_value = int(input("Enter a number to add to the list: "))
numbers.append(add_value)
print("List after adding:", numbers)

#  Remove element given by user
remove_value = int(input("Enter a number to remove from the list: "))

if remove_value in numbers:
    numbers.remove(remove_value)
    print(f"List after removing {remove_value}:", numbers)
else:
    print(f"{remove_value} not found in the list! No removal.")

#  Max, Min, Sorted Output
print("\n--- List Stats ---")
print("Maximum value:", max(numbers))
print("Minimum value:", min(numbers))
sorted_list = sorted(numbers)
print("Sorted List:", sorted_list)

#  NumPy conversion
arr = np.array(numbers)

print("\n--- NumPy Statistics ---")
print(f"Mean: {np.mean(arr)}")
print(f"Median: {np.median(arr)}")
print(f"Standard Deviation: {np.std(arr)}")

# ---------------- Task 3: Dictionaries and Sets ----------------

# Create student dictionary
student = {
    "name": input("Enter student name: "),
    "course": input("Enter course name: "),
    "marks": int(input("Enter marks: "))
}

#  Add grade based on marks
if student["marks"] >= 80:
    student["grade"] = "A"
elif student["marks"] >= 60:
    student["grade"] = "B"
else:
    student["grade"] = "C"

# Print keys and values
print("\n--- Student Details ---")
for key, value in student.items():
    print(f"{key} : {value}")

# Create two sets of AI tools
ai_tools_set1 = {"ChatGPT", "TensorFlow", "PyTorch", "BERT", "LangChain"}
ai_tools_set2 = {"Gemini", "BERT", "HuggingFace", "Claude"}

print("\n--- AI Tools Set 1 ---")
print(ai_tools_set1)

print("\n--- AI Tools Set 2 ---")
print(ai_tools_set2)

#  ---------------- Task 4: File Handling----------------

# List of students: (Name, Marks, Grade)
students = [
    ("Asha", 85, "A"),
    ("Rahul", 70, "B"),
    ("Priya", 92, "A"),
    ("Karan", 67, "B"),
    ("Sona", 88, "A")
]

# Creating & Writing into file
with open("ai_students.txt", "w") as file:
    for s in students:
        file.write(f"{s[0]}, {s[1]}, {s[2]}\n")

print(" File 'ai_students.txt' created & data written successfully!")

# #  ---------------- Task 4: File Handling - continuation----------------
print("Students scoring above 75 marks:\n")

with open("ai_students.txt", "r") as file:
    for line in file:
        name, marks, grade = line.strip().split(", ")
        if int(marks) > 75:
            print(f"{name} | Marks: {marks} | Grade: {grade}")

#  ---------------- Task 5: Mini Project----------------

#  AI Prompt Logger
#This program logs AI prompts entered by a user and saves them into a file with timestamps.
import os
from datetime import datetime

file_name = "prompt_history.txt"

def log_prompt(prompt):
    with open(file_name, "a") as file:
        file.write(f"{datetime.now()} => {prompt}\n")
    print("Prompt saved successfully!")

def show_history():
    if not os.path.exists(file_name):
        print(" No history found.")
        return

    print("\n --- Prompt History ---\n")
    with open(file_name, "r") as file:
        lines = file.readlines()
        for line in lines:
            print(line.strip())
    print(f"\n Total Prompts Logged: {len(lines)}\n")

def clear_history():
    if os.path.exists(file_name):
        os.remove(file_name)
        print(" History cleared successfully!")
    else:
        print(" No history to clear")

while True:
    print("\n AI Prompt Logger Menu")
    print("1️⃣ Log new prompt")
    print("2️⃣ View history")
    print("3️⃣ Clear history")
    print("4️⃣ Exit")

    choice = input("Enter your choice: ")

    if choice == "1":
        user_prompt = input("Enter your AI prompt: ")
        log_prompt(user_prompt)

    elif choice == "2":
        show_history()

    elif choice == "3":
        clear_history()

    elif choice == "4":
        print(" Exiting... Goodbye!")
        break

    else:
        print(" Invalid choice. Try again.")